"use client";
import { Session } from "next-auth";

interface IProps {
  session: Session;
}

export default function Dashboard({ session }: IProps) {
  return (
    <div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div> <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div> <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div> <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div> <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div> <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div> <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div> <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div> <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div> <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
      <div>Dashboard</div>
    </div>
  );
}
